alias gitps="git push"
alias gitp="git pull"
alias gitc="git commit -a"
alias gitb='git branch'
alias gitad='git add'
alias gitd='git difftool --no-prompt'
alias gitm="git commit -m"
alias giti="git init"
alias gitst='git status'
