#!/bin/bash

#       ogg2mp3 written in bash
#       version 0.2
#       Copyright 2009 Mephiston <meph.snake@gmail.com>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 3 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, get a copy on http://www.gnu.org/licenses/gpl.txt

# ---------------- Generic utilities ---------------- #
# The main purpose of this script is to easily conver OGG files into MP3 files.
# Because some devices don't accept ogg format.
# This script converts massively the ogg files of your actual directory.

# ---------------- Instructions ---------------- #
# For using this script you must have installed Bash, lame, and oggdec.
# As optional extra you can decide to use normalize-audio.
# If you don't want to normalize audio files, you must comment lines refering to normalize-audio.

if [ -z "$1" ]
    then
    value=160
    valuet=$(( ($value*1000) ))
    #If bitrate is not specified will use
        mensaje="Bitrate value not supplied. Default: 160kbps."
        mensaj="Note: If you want to specify some specify bitrate in kbps, just write something like 'ogg2mp3 120 '"
else
    value=$1
    valuet=$(( ($1*1000) ))
    mensaje="Bitrate value suplied. Using $value"
    mensaj=""
fi

if ! which oggdec &>/dev/null; then
echo "ogg2mp3: You must install first 'vorbis-tools'"

elif ! which lame &>/dev/null; then
echo "ogg2mp3: You must install first 'lame'. "

elif ! which normalize-audio &>/dev/null; then
echo "ogg2mp3: You must install first 'normalize-audio'. "

else
echo "---------------------------------"
echo "| ogg2mp3-lame v0.2 BASH VERSION|"
echo "| Author: Mephiston             |"
echo "---------------------------------"

#Lowercasing names
rename 'y/A-Z/a-z/' *.ogg

#Erasing spaces between words
rename 'y/\ /_/' *.ogg

#Converting ogg files to wav format.
echo $mensaje$mensaj && sleep 3
for archivo in *.ogg; do oggdec $archivo; done

#If you don't want to normalize audio, just comment this line'
normalize-audio -m *.wav

for archivo in *.wav; do
    #A variable, for giving name to files
    wavname="$(basename "$archivo" .wav)"
    #Now it checks if bitrate is supplied.
    #If not supplied it will use a default value.
    lame -b $valuet "$wavname.wav" "$wavname.mp3"
    #Now it checks if exists some errors.
    #If all is correct delete the wav.
    if [ $? -eq 0 ]
    then
        echo "File conversion with bitrate on $value finished"
        echo "In the conversion we created temporaly WAV files"
        echo "Do you want to delete WAV files? y/n"
        read respuesta;
        case $respuesta in
            Y|y) rm -f "$wavname.wav";;
            S|s) rm -f "$wavname.wav";;
            *) echo "The files were not deleted";;
        esac
    fi
done
fi

